# Generated by Django 4.2.2 on 2023-07-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boardgame',
            table='boardgames',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
