# Generated by Django 4.2.2 on 2023-07-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_boardgame_table_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boardgamecategory',
            table='boardgame_categories',
        ),
    ]
