# Generated by Django 4.2.2 on 2023-07-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_boardgamecategory_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'verbose_name': 'ボードゲーム', 'verbose_name_plural': 'ボードゲーム'},
        ),
        migrations.AlterModelOptions(
            name='boardgamecategory',
            options={'verbose_name': 'ボードゲームとカテゴリー', 'verbose_name_plural': 'ボードゲームとカテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリー', 'verbose_name_plural': 'カテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'レビュー', 'verbose_name_plural': 'レビュー'},
        ),
    ]
